name: 'Workflow Distributed Lock Action'
description: 'A GitHub Action to implement a distributed lock across workflows.'
author: 'Connor Hollasch'

branding:
  icon: 'lock'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token with repo scope.'
    required: true
  lock-file-path:
    description: 'The path to the lock file in the repository.'
    required: true
  lock-branch:
    description: 'The branch where the lock file is stored.'
    required: false
    default: 'locks'
  lock-key:
    description: 'The key for the lock.'
    required: true
  max-concurrent:
    description: 'The maximum number of concurrent entries allowed.'
    required: false
  polling-interval:
    description: 'Time in seconds between retries.'
    required: false
    default: '10'
  mode:
    description: 'Action mode: acquire or release.'
    required: false
    default: 'acquire'

runs:
  using: node20
  main: dist/index.js
