name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lock-file-path: '__tests__/lock/lock.json'
          lock-branch: 'lock'
          lock-key: 'test-lock'
          max-concurrent: '1'
          polling-interval: '10'
          mode: 'acquire'

      - name: Critical Section
        run: |
          echo "Executing critical section..."

      - name: Release Lock
        if: always()
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lock-file-path: '__tests__/lock/lock.json'
          lock-branch: 'lock'
          lock-key: 'test-lock'
          mode: 'release'
